name: noshow_ket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
    - assets/cookies.png
    - assets/ItemList.png
=======
    - assets/
>>>>>>> feature/home-page
